name: SuperChest
main: me.ecminer.superchest.SuperChest
version: 0.0.1
description: This plugin will allow you to store an unlimited amount of items in a single chest!
author: [EcMiner]
permissions:
  superchest.*:
    default: op
    description: Gives you access to all the SuperChest permissions.
    children:
      superchest.place: true
      superchest.break: true
  superchest.place:
    default: op
    description: Gives you access to place a SuperChest
  superchest.break:
    default: op
    description: Gives you access to break a SuperChest